var annotated_dup =
[
    [ "tek_sa_additional_file", "group__DEF.html#structtek__sa__additional__file", "group__DEF_structtek__sa__additional__file" ],
    [ "tek_sa_byte_string", "group__DEF.html#structtek__sa__byte__string", "group__DEF_structtek__sa__byte__string" ],
    [ "tek_sa_complex_data", "group__DEF.html#structtek__sa__complex__data", "group__DEF_structtek__sa__complex__data" ],
    [ "tek_sa_complex_data_array", "group__DEF.html#structtek__sa__complex__data__array", "group__DEF_structtek__sa__complex__data__array" ],
    [ "tek_sa_complex_data_array_item", "group__DEF.html#structtek__sa__complex__data__array__item", "group__DEF_structtek__sa__complex__data__array__item" ],
    [ "tek_sa_complex_data_matrix", "group__DEF.html#structtek__sa__complex__data__matrix", "group__DEF_structtek__sa__complex__data__matrix" ],
    [ "tek_sa_configuration", "group__DEF.html#structtek__sa__configuration", "group__DEF_structtek__sa__configuration" ],
    [ "tek_sa_data_client", "structtek__sa__data__client.html", "structtek__sa__data__client" ],
    [ "tek_sa_data_client_capabilities", "group__DC.html#structtek__sa__data__client__capabilities", "group__DC_structtek__sa__data__client__capabilities" ],
    [ "tek_sa_data_client_configuration", "group__DEF.html#structtek__sa__data__client__configuration", "group__DEF_structtek__sa__data__client__configuration" ],
    [ "tek_sa_data_client_plugin", "structtek__sa__data__client__plugin.html", "structtek__sa__data__client__plugin" ],
    [ "tek_sa_dc_event", "group__DEF.html#structtek__sa__dc__event", "group__DEF_structtek__sa__dc__event" ],
    [ "tek_sa_enum_definition", "group__DEF.html#structtek__sa__enum__definition", "group__DEF_structtek__sa__enum__definition" ],
    [ "tek_sa_enum_item_definition", "group__DEF.html#structtek__sa__enum__item__definition", "group__DEF_structtek__sa__enum__item__definition" ],
    [ "tek_sa_event_parameter", "group__DEF.html#structtek__sa__event__parameter", "group__DEF_structtek__sa__event__parameter" ],
    [ "tek_sa_field_write_request", "group__DEF.html#structtek__sa__field__write__request", "group__DEF_structtek__sa__field__write__request" ],
    [ "tek_sa_guid", "group__DEF.html#structtek__sa__guid", "group__DEF_structtek__sa__guid" ],
    [ "tek_sa_method_argument_description", "group__DEF.html#structtek__sa__method__argument__description", "group__DEF_structtek__sa__method__argument__description" ],
    [ "tek_sa_read_result", "group__DEF.html#structtek__sa__read__result", "group__DEF_structtek__sa__read__result" ],
    [ "tek_sa_string", "group__DEF.html#structtek__sa__string", "group__DEF_structtek__sa__string" ],
    [ "tek_sa_struct_definition", "group__DEF.html#structtek__sa__struct__definition", "group__DEF_structtek__sa__struct__definition" ],
    [ "tek_sa_struct_field_type_definition", "group__DEF.html#structtek__sa__struct__field__type__definition", "group__DEF_structtek__sa__struct__field__type__definition" ],
    [ "tek_sa_transformation_engine", "structtek__sa__transformation__engine.html", "structtek__sa__transformation__engine" ],
    [ "tek_sa_variant", "group__DEF.html#structtek__sa__variant", "group__DEF_structtek__sa__variant" ],
    [ "tek_sa_variant.data", "group__DEF.html#uniontek__sa__variant_8data", "group__DEF_uniontek__sa__variant_8data" ],
    [ "tek_sa_variant_array", "group__DEF.html#structtek__sa__variant__array", "group__DEF_structtek__sa__variant__array" ],
    [ "tek_sa_variant_array.data", "group__DEF.html#uniontek__sa__variant__array_8data", "group__DEF_uniontek__sa__variant__array_8data" ],
    [ "tek_sa_variant_matrix", "group__DEF.html#structtek__sa__variant__matrix", "group__DEF_structtek__sa__variant__matrix" ],
    [ "tek_sa_write_result", "group__DEF.html#structtek__sa__write__result", "group__DEF_structtek__sa__write__result" ]
];